import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import {inspectPackage,makePlan,applyPlan} from '../../src/core.mjs';import {modify} from '../helpers.mjs';
const fixture=new Uint8Array(await readFile('tests/fixtures/workshop.pptx')),expected=JSON.parse(await readFile('tests/fixtures/expected-selection.json','utf8')),out='tests/browser/artifacts';await mkdir(out,{recursive:true});const base=process.env.BASE_URL||'http://127.0.0.1:4177',checks=[],errors=[],requests=[];
const browser=await chromium.launch({headless:true,chromiumSandbox:true}),context=await browser.newContext({viewport:{width:1440,height:1040},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>requests.push(r.url()));
const step=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name);};
async function demo(){await page.locator('#demo').click();await expect(page.locator('.summary h2')).toHaveText('workshop.pptx');await expect(page.locator('#busy')).toBeHidden();}
async function previewDemo(){await page.locator('#demo-selection').click();await page.locator('#preview').click();await expect(page.locator('.preview-row')).toHaveCount(3);}
async function exportNow(){await page.locator('#export').click();await expect(page.locator('#export-result')).toBeVisible();await expect(page.locator('#busy')).toBeHidden();}
async function download(id,name){const promise=page.waitForEvent('download');await page.locator('#'+id).click();const d=await promise;await d.saveAs(`${out}/${name}`);return new Uint8Array(await readFile(`${out}/${name}`));}
async function importBytes(bytes,name='reimport.pptx'){await page.locator('#file').setInputFiles({name,mimeType:'application/vnd.openxmlformats-officedocument.presentationml.presentation',buffer:Buffer.from(bytes)});await expect(page.locator('.summary h2')).toHaveText(name);await expect(page.locator('#busy')).toBeHidden();}
try{
await step('Japanese entry, keyboard skip, eight-slide inventory and bilingual responsive screenshots',async()=>{await page.goto(base);await expect(page.locator('html')).toHaveAttribute('lang','ja');await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await expect(page.locator('.skip')).toHaveCSS('opacity','1');await page.keyboard.press('Enter');await expect(page.locator('#workspace')).toBeFocused();await expect(page.locator('.skip')).toHaveCSS('opacity','0');await demo();await expect(page.locator('[data-carrier]')).toHaveCount(29);await expect(page.locator('[data-carrier]:disabled')).toHaveCount(7);await page.screenshot({path:`${out}/desktop-ja.png`,fullPage:true});await page.setViewportSize({width:390,height:1040});await page.screenshot({path:`${out}/mobile-ja.png`,fullPage:true});await page.setViewportSize({width:1440,height:1040});await page.locator('[data-lang="en"]').click();await expect(page.locator('html')).toHaveAttribute('lang','en');});
await step('exact three-carrier preview exposes shared references and immutable slide identities',async()=>{await previewDemo();await expect(page.locator('[data-carrier]:checked')).toHaveCount(3);await expect(page.locator('#target')).toHaveValue('260');await expect(page.locator('#preview-panel')).toContainText('Module B menu');await expect(page.locator('#preview-panel')).toContainText('ID 260');await expect(page.locator('.shared').first()).toBeVisible();await page.screenshot({path:`${out}/desktop-en-preview.png`,fullPage:true});});
let output,receipt,plan;
await step('actual editable PPTX, receipt and plan downloads match the engine and independent oracle',async()=>{await exportNow();output=await download('download-pptx','remapped.pptx');receipt=JSON.parse(new TextDecoder().decode(await download('download-receipt','receipt.json')));plan=JSON.parse(new TextDecoder().decode(await download('download-plan','plan.json')));const c=await inspectPackage(fixture,'workshop.pptx'),ref=await applyPlan(c,makePlan(c,expected.map(x=>({carrierId:x.sourcePart+'#'+x.carrierPath.join('.'),toSlideId:x.toSlideId}))));assert.deepEqual(output,ref.output);assert.deepEqual(receipt,ref.receipt);execFileSync('python3',['tests/oracle.py','tests/fixtures/workshop.pptx',`${out}/remapped.pptx`,`${out}/receipt.json`,'--expected-selection','tests/fixtures/expected-selection.json'],{stdio:'inherit'});await exportNow();assert.deepEqual(await download('download-pptx','repeated.pptx'),output);const different={...plan,edits:plan.edits.map(e=>({...e,toSlideId:'258'}))};await page.locator('#plan-file').setInputFiles({name:'different-plan.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(different))});await expect(page.locator('#export-result')).toHaveCount(0);await expect(page.locator('.preview-row')).toHaveCount(3);await expect(page.locator('#target')).toHaveValue('258');await expect(page.locator('#download-pptx')).toHaveCount(0);await page.locator('#plan-file').setInputFiles({name:'original-plan.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(plan))});await expect(page.locator('#target')).toHaveValue('260');});
await step('selection or target changes invalidate old preview/export while filters retain explicit hidden selections',async()=>{await page.locator('#source-filter').selectOption('257');await expect(page.locator('.hidden-note')).toContainText('3');await page.locator('#target').selectOption('257');await expect(page.locator('#preview-panel')).toHaveCount(0);await expect(page.locator('#export-result')).toHaveCount(0);await page.locator('#source-filter').selectOption('');await page.locator('#query').fill('nonexistent');await expect(page.locator('.carrier-list')).toContainText('No matching');await page.locator('#query').fill('Return');await page.locator('#mode').selectOption('eligible');await expect(page.locator('[data-carrier]:disabled')).toHaveCount(0);await page.locator('#query').fill('');await page.locator('#mode').selectOption('all');});
await step('hash-bound plan replay works on original input and blocks stale or unsupported choices',async()=>{await page.locator('#plan-file').setInputFiles({name:'plan.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(plan))});await expect(page.locator('.preview-row')).toHaveCount(3);await expect(page.locator('#target')).toHaveValue('260');await page.locator('#clear-selection').click();await page.locator('#plan-file').setInputFiles({name:'stale.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...plan,inputSha256:'0'.repeat(64)}))});await expect(page.locator('#notice')).toContainText('stale-plan');await expect(page.locator('#preview-panel')).toHaveCount(0);const malformed=Buffer.from(JSON.stringify({...plan,metadata:'MARK'}));malformed[malformed.indexOf('MARK')]=0xff;await page.locator('#plan-file').setInputFiles({name:'invalid-utf8.json',mimeType:'application/json',buffer:malformed});await expect(page.locator('#notice')).toContainText('encoding');await expect(page.locator('#preview-panel')).toHaveCount(0);const c=await inspectPackage(fixture),bad=c.model.carriers.find(x=>!x.eligible);await page.locator('#plan-file').setInputFiles({name:'unsupported.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...plan,edits:[{carrierId:bad.id,toSlideId:'260'}]}))});await expect(page.locator('#notice')).toContainText('unsupported-selection');await expect(page.locator('#preview-panel')).toHaveCount(0);});
await step('no-op export is byte-identical and clearly reports zero changes',async()=>{await page.locator('#demo-selection').click();await page.locator('#target').selectOption('256');await page.locator('#preview').click();await expect(page.locator('.preview-row')).toHaveCount(3);await expect(page.locator('.preview-heading')).toContainText('0 Actual changes');await exportNow();assert.deepEqual(await download('download-pptx','no-op.pptx'),fixture);const r=JSON.parse(new TextDecoder().decode(await download('download-receipt','no-op-receipt.json')));assert.equal(r.changes.length,0);assert.equal(r.inputSha256,r.outputSha256);});
await step('reopen exported PPTX, repeated same-file imports and malformed replacement retention',async()=>{await importBytes(output,'remapped.pptx');await page.locator('#dest-filter').selectOption('260');await expect(page.locator('.carrier')).toHaveCount(3);for(let i=0;i<2;i++)await importBytes(fixture,'repeat.pptx');await page.locator('#file').setInputFiles({name:'bad.pptx',mimeType:'application/octet-stream',buffer:Buffer.from('broken')});await expect(page.locator('#notice')).toHaveClass(/error/);await expect(page.locator('.summary h2')).toHaveText('repeat.pptx');await previewDemo();await exportNow();});
await step('interrupted worker, oversized replacement and reset cancellation preserve state without resurrection',async()=>{await page.evaluate(()=>{window.__post=Worker.prototype.postMessage;const original=window.__post;Worker.prototype.postMessage=function(...args){setTimeout(()=>{try{original.apply(this,args);}catch{}},400);};});await page.locator('#demo').click();await expect(page.locator('#busy')).toBeVisible();await page.locator('#cancel').click();await expect(page.locator('.summary h2')).toHaveText('repeat.pptx');await page.locator('#demo').click();await page.locator('#file').setInputFiles({name:'huge.pptx',mimeType:'application/octet-stream',buffer:Buffer.alloc(25*1024*1024+1)});await expect(page.locator('#notice')).toContainText('input-size');await page.waitForTimeout(550);await expect(page.locator('.summary h2')).toHaveText('repeat.pptx');await expect(page.locator('#notice')).toContainText('input-size');await page.evaluate(()=>{Worker.prototype.postMessage=window.__post;delete window.__post;});await page.locator('#reset').click();await page.keyboard.press('Escape');await expect(page.locator('.summary h2')).toHaveText('repeat.pptx');await page.locator('#reset').click();await page.locator('#confirm-reset').click();await expect(page.locator('.empty')).toBeVisible();});
await step('offline import, preview and export need no extra module requests',async()=>{await context.setOffline(true);await importBytes(fixture,'offline.pptx');await previewDemo();await exportNow();const r=JSON.parse(new TextDecoder().decode(await download('download-receipt','offline-receipt.json')));assert.equal(r.changes.length,3);await context.setOffline(false);});
await step('hostile imported text is escaped and external targets are never visited',async()=>{const hostile=await modify(fixture,'ppt/slides/slide10.xml',s=>s.replace('>Return</a:t>','>&lt;img src=x onerror=alert(1)&gt;</a:t>'));await importBytes(hostile,'hostile.pptx');await page.locator('#source-filter').selectOption('261');await expect(page.locator('.carrier-list')).toContainText('<img src=x');await expect(page.locator('.carrier img')).toHaveCount(0);assert.ok(requests.every(u=>u.startsWith(base+'/')||u.startsWith('blob:')));});
await step('keyboard selection, narrow layouts and printed change preview keep scope visible',async()=>{await demo();await page.locator('[data-carrier]:not(:disabled)').first().focus();await page.keyboard.press('Space');await expect(page.locator('[data-carrier]:checked')).toHaveCount(1);await previewDemo();for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1040});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);await page.screenshot({path:`${out}/responsive-${width}.png`,fullPage:true});}await page.setViewportSize({width:1440,height:1040});await page.emulateMedia({media:'print'});await expect(page.locator('.scope')).toBeVisible();await expect(page.locator('#preview-panel')).toBeVisible();await page.pdf({path:`${out}/change-preview.pdf`,format:'A4',printBackground:true});await page.screenshot({path:`${out}/change-preview-print.png`,fullPage:true});await page.emulateMedia({media:'screen'});});
await step('no duplicate IDs, persisted deck, external requests or uncaught page errors',async()=>{assert.equal(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(n=>n.id);return ids.length===new Set(ids).size;}),true);await page.reload();await expect(page.locator('.empty')).toBeVisible();assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith(base+'/')||u.startsWith('blob:')));});
await writeFile(`${out}/results.json`,JSON.stringify({status:'passed',chromiumSandbox:true,checks,uncaughtErrors:errors,nativePowerPointTested:false},null,2));
}catch(e){await page.screenshot({path:`${out}/failure.png`,fullPage:true}).catch(()=>{});await writeFile(`${out}/results.json`,JSON.stringify({status:'failed',chromiumSandbox:true,checks,error:String(e),uncaughtErrors:errors},null,2));throw e;}finally{await context.close();await browser.close();}
