import {VERSION,LIMITS,fail} from './limits.mjs';
import {openZip,writeZip,encode,decode,sha256,safePath} from './zip.mjs';
import {xml,is,direct,attr,walk} from './xml.mjs';
export {VERSION,LIMITS};
export const NS={p:'http://schemas.openxmlformats.org/presentationml/2006/main',a:'http://schemas.openxmlformats.org/drawingml/2006/main',r:'http://schemas.openxmlformats.org/officeDocument/2006/relationships',pkg:'http://schemas.openxmlformats.org/package/2006/relationships',ct:'http://schemas.openxmlformats.org/package/2006/content-types',mc:'http://schemas.openxmlformats.org/markup-compatibility/2006'};
const RELSLIDE=NS.r+'/slide',OFFICE=NS.r+'/officeDocument',MAIN='application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml',JUMP='ppaction://hlinksldjump';
export const escapeXML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const bounded=(s,n=LIMITS.textChars)=>{if(typeof s!=='string'||s.length>n)fail('metadata-limit');return s;};
const sole=(a,code)=>{if(a.length!==1)fail(code);return a[0];};
export function resolvePart(source,target){if(!target||target.startsWith('//')||target.length>LIMITS.pathChars||/[\\\x00-\x20\x7f?#]/.test(target)||/^[a-z][a-z0-9+.-]*:/i.test(target)||/%(?:2f|5c|00)/i.test(target))fail('relationship-target');let decoded;try{decoded=decodeURIComponent(target);}catch{fail('relationship-target');}const segments=target.startsWith('/')?[]:source.split('/').slice(0,-1);for(const part of decoded.split('/')){if(!part||part==='.')continue;if(part==='..'){if(!segments.length)fail('relationship-target');segments.pop();}else segments.push(part);}const result=segments.join('/');if(!safePath(result)||result.endsWith('/'))fail('relationship-target');return result;}
export function relationshipPart(source){if(!source)return '_rels/.rels';const chunks=source.split('/'),name=chunks.pop();return [...chunks,'_rels',name+'.rels'].join('/');}
function relationshipSource(part){if(part==='_rels/.rels')return '';const chunks=part.split('/');if(chunks.at(-2)!=='_rels'||!chunks.at(-1).endsWith('.rels'))fail('relationship-part');chunks.splice(-2,1);chunks[chunks.length-1]=chunks.at(-1).slice(0,-5);return chunks.join('/');}
function parseEntry(entry,budget){if(!entry||entry.size>LIMITS.xmlBytes)fail('xml-size');budget.bytes+=entry.size;if(budget.bytes>LIMITS.xmlBytesTotal)fail('xml-total-limit');const text=decode(entry.bytes),root=xml(text);budget.nodes+=walk(root).length;budget.namespaceUnits+=root.namespaceWorkUnits;if(budget.nodes>LIMITS.xmlNodesTotal||budget.namespaceUnits>LIMITS.namespaceWorkUnitsTotal)fail('xml-total-limit');return {text,root};}
function readRelationships(zip,budget){const all=new Map();let total=0;for(const e of zip.entries.values()){if(!e.name.endsWith('.rels'))continue;const source=relationshipSource(e.name),doc=parseEntry(e,budget);if(!is(doc.root,NS.pkg,'Relationships'))fail('relationship-root');const byId=new Map(),list=[];for(const n of doc.root.children){if(!is(n,NS.pkg,'Relationship')||n.children.length||n.text.trim())fail('relationship-element');const id=bounded(n.attrs.Id??'',LIMITS.idChars),type=bounded(n.attrs.Type??'',2048),target=bounded(n.attrs.Target??'',2048),mode=n.attrs.TargetMode??'Internal';if(!/^[A-Za-z_][\w.-]*$/.test(id)||byId.has(id)||!type||!target||!['Internal','External'].includes(mode))fail('relationship-id');if(++total>LIMITS.relationships)fail('relationship-limit');const part=mode==='Internal'?resolvePart(source,target):null;if(part&&!zip.entries.has(part))fail('missing-relationship-target');const rel={id,type,target,mode,part,node:n};byId.set(id,rel);list.push(rel);}all.set(source,{part:e.name,...doc,byId,list});}return all;}
function contentTypes(zip,budget){const d=parseEntry(zip.entries.get('[Content_Types].xml'),budget);if(!is(d.root,NS.ct,'Types'))fail('content-types');const defaults=new Map(),overrides=new Map();for(const n of d.root.children){if(is(n,NS.ct,'Default')){if(defaults.has(n.attrs.Extension))fail('content-types');defaults.set(n.attrs.Extension,n.attrs.ContentType);}else if(is(n,NS.ct,'Override')){const part=resolvePart('',n.attrs.PartName);if(overrides.has(part))fail('content-types');overrides.set(part,n.attrs.ContentType);}else fail('content-types');if(/macroenabled|vbaproject|digital-signature|encrypted/i.test(n.attrs.ContentType??''))fail('excluded-package');}return part=>overrides.get(part)??defaults.get(part.split('.').at(-1));}
function ownedShape(shape){let n=shape?.parent;while(is(n,NS.p,'grpSp'))n=n.parent;return is(n,NS.p,'spTree')&&is(n.parent,NS.p,'cSld')&&is(n.parent.parent,NS.p,'sld');}
function nearest(node,test){for(let n=node.parent;n;n=n.parent)if(test(n))return n;return null;}
function labelFor(node){return bounded(walk(node).filter(n=>is(n,NS.a,'t')).map(n=>n.text).join(' ').slice(0,LIMITS.textChars));}
export async function inspectPackage(input,name='deck.pptx'){
 const zip=await openZip(input),budget={bytes:0,nodes:0,namespaceUnits:0};for(const e of zip.entries.values())if(/(?:^|\/)(?:_xmlsignatures|vbaProject\.bin|EncryptionInfo|EncryptedPackage)(?:\/|$)/i.test(e.name))fail('excluded-package');const typeOf=contentTypes(zip,budget),rels=readRelationships(zip,budget);for(const r of rels.values())if(r.list.some(x=>/vbaProject|digital-signature/i.test(x.type)))fail('excluded-package');const office=sole(rels.get('')?.list.filter(r=>r.type===OFFICE&&r.mode==='Internal')??[],'presentation-root');if(typeOf(office.part)!==MAIN)fail('presentation-type');const presentation=parseEntry(zip.entries.get(office.part),budget);if(!is(presentation.root,NS.p,'presentation'))fail('presentation-namespace');const list=sole(direct(presentation.root,NS.p,'sldIdLst'),'slide-list'),presRels=rels.get(office.part);if(!presRels||!list.children.length||list.children.length>LIMITS.slides)fail('slide-limit');const slides=[],ids=new Set(),parts=new Set();
 for(const [i,node]of list.children.entries()){if(!is(node,NS.p,'sldId'))fail('slide-list');const id=bounded(node.attrs.id??'',LIMITS.idChars),rid=attr(node,NS.r,'id'),rel=presRels.byId.get(rid);if(!/^\d+$/.test(id)||ids.has(/^\d+$/.test(id)?BigInt(id).toString():id)||!rel||rel.type!==RELSLIDE||!rel.part||parts.has(rel.part))fail('slide-identity');ids.add(BigInt(id).toString());parts.add(rel.part);if(typeOf(rel.part)!=='application/vnd.openxmlformats-officedocument.presentationml.slide+xml')fail('slide-type');const doc=parseEntry(zip.entries.get(rel.part),budget);if(!is(doc.root,NS.p,'sld'))fail('slide-root');const all=walk(doc.root),shapeIds=new Set();for(const n of all.filter(n=>is(n,NS.p,'cNvPr'))){const sid=bounded(n.attrs.id??'',LIMITS.idChars);if(!/^\d+$/.test(sid)||shapeIds.has(/^\d+$/.test(sid)?BigInt(sid).toString():sid))fail('shape-id');shapeIds.add(BigInt(sid).toString());bounded(n.attrs.name??'');}const titleShape=all.find(n=>is(n,NS.p,'sp')&&walk(n).some(c=>is(c,NS.p,'ph')&&['title','ctrTitle'].includes(c.attrs.type)));const fallback=all.find(n=>is(n,NS.a,'t'))?.text??'';slides.push({id,part:rel.part,order:i+1,title:titleShape?labelFor(titleShape):bounded(fallback.slice(0,LIMITS.textChars)),doc,rels:rels.get(rel.part),all});}
 const byPart=new Map(slides.map(s=>[s.part,s])),carriers=[];for(const slide of slides){const allLinks=slide.all.filter(n=>is(n,NS.a,'hlinkClick')||is(n,NS.a,'hlinkHover'));for(const n of allLinks){if(carriers.length>=LIMITS.carriers)fail('carrier-limit');const event=n.local==='hlinkClick'?'click':'hover',rid=attr(n,NS.r,'id'),rel=slide.rels?.byId.get(rid),target=rel?.type===RELSLIDE&&rel.mode==='Internal'?byPart.get(rel.part):null;const action=bounded(n.attrs.action??'',1024);let kind='other',shape=null;if(is(n.parent,NS.p,'cNvPr')){shape=n.parent.parent?.parent;if(shape?.ns===NS.p&&['sp','pic','cxnSp'].includes(shape.local)&&is(n.parent.parent,NS.p,{sp:'nvSpPr',pic:'nvPicPr',cxnSp:'nvCxnSpPr'}[shape.local])&&ownedShape(shape))kind='shape';else shape=null;}else if(is(n.parent,NS.a,'rPr')&&is(n.parent.parent,NS.a,'r')){kind='run';shape=nearest(n,x=>x.ns===NS.p&&['sp','pic','cxnSp','graphicFrame'].includes(x.local));if(!shape||!ownedShape(shape)){kind='other';shape=null;}}const cnv=shape?walk(shape).find(x=>is(x,NS.p,'cNvPr')):null;const unsupportedContext=!!nearest(n,x=>is(x,NS.mc,'AlternateContent')||x.local==='extLst')||(shape&&walk(shape).some(x=>/zoom/i.test(x.local)));let reason=event==='hover'?'hover':action!==JUMP?(action.includes('hlinkshowjump')?'relative-action':action.includes('customshow')?'custom-show':action?'other-action':'external-or-generic'):kind==='other'?'carrier-context':unsupportedContext?'extension-context':direct(n.parent,NS.a,n.local).length!==1?'duplicate-carrier':!rid||!rel?'missing-relationship':rel.mode!=='Internal'?'external-target':rel.type!==RELSLIDE?'relationship-type':!target?'target-not-listed':null;
 const path=n.path,id=slide.part+'#'+path.join('.');carriers.push({id,sourceSlideId:slide.id,sourcePart:slide.part,sourceOrder:slide.order,carrierPath:path,kind,event,shapeId:cnv?.attrs.id??null,shapeName:cnv?.attrs.name??'',text:kind==='run'?bounded(n.parent.parent.children.filter(c=>is(c,NS.a,'t')).map(c=>c.text).join('').slice(0,LIMITS.textChars)):shape?labelFor(shape):'',action,relationshipId:rid,currentSlideId:target?.id??null,currentPart:target?.part??null,eligible:reason===null,reason,node:n});}}
 const usage=new Map();for(const c of carriers)if(c.relationshipId){const key=c.sourcePart+'\0'+c.relationshipId;usage.set(key,(usage.get(key)??0)+1);}for(const c of carriers)c.sharedRelationshipUses=usage.get(c.sourcePart+'\0'+c.relationshipId)??0;
 const outside=[];for(const e of zip.entries.values()){if(!/(?:slideMasters|slideLayouts)\/[^/]+\.xml$/.test(e.name))continue;const d=parseEntry(e,budget);const count=walk(d.root).filter(n=>is(n,NS.a,'hlinkClick')||is(n,NS.a,'hlinkHover')).length;if(count)outside.push({part:e.name,count,reason:'master-layout'});}
 const hash=await sha256(zip.bytes),model={schema:'deck-relay-inspection-v1',engineVersion:VERSION,input:{name:bounded(String(name),512),bytes:zip.bytes.length,sha256:hash},slides:slides.map(({doc,rels,all,...s})=>s),carriers:carriers.map(({node,...c})=>c),outsideScope:outside,counts:{slides:slides.length,carriers:carriers.length,eligible:carriers.filter(c=>c.eligible).length,unsupported:carriers.filter(c=>!c.eligible).length,outsideSlideActions:outside.reduce((s,x)=>s+x.count,0)},limits:LIMITS};return {zip,slides,carriers,model};
}
export function makePlan(ctx,edits){if(!Array.isArray(edits)||edits.length>LIMITS.carriers)fail('plan-limit');const map=new Map(ctx.carriers.map(c=>[c.id,c])),ids=new Set(),targetIds=new Set(ctx.slides.map(s=>s.id));const clean=[];for(const edit of edits){if(!edit||typeof edit.carrierId!=='string'||typeof edit.toSlideId!=='string'||ids.has(edit.carrierId))fail('plan-carrier');ids.add(edit.carrierId);const c=map.get(edit.carrierId);if(!c)fail('plan-carrier');if(!c.eligible)fail('unsupported-selection');if(!targetIds.has(edit.toSlideId))fail('plan-target');clean.push({carrierId:c.id,toSlideId:edit.toSlideId});}return {schema:'deck-relay-plan-v1',inputSha256:ctx.model.input.sha256,edits:clean};}
export function preview(ctx,plan){if(plan?.schema!=='deck-relay-plan-v1'||plan.inputSha256!==ctx.model.input.sha256)fail('stale-plan');const validated=makePlan(ctx,plan.edits),byId=new Map(ctx.carriers.map(c=>[c.id,c]));return {plan:validated,rows:validated.edits.map(e=>{const c=byId.get(e.carrierId);return {carrierId:c.id,sourceSlideId:c.sourceSlideId,sourcePart:c.sourcePart,carrierPath:c.carrierPath,kind:c.kind,text:c.text,shapeId:c.shapeId,shapeName:c.shapeName,fromSlideId:c.currentSlideId,toSlideId:e.toSlideId,noOp:c.currentSlideId===e.toSlideId,sharedRelationshipUses:c.sharedRelationshipUses};})};}
function patchText(text,patches){const sorted=[...patches].sort((a,b)=>b.start-a.start);let boundary=text.length;for(const p of sorted){if(p.start<0||p.end>boundary||p.end<p.start)fail('patch-overlap');text=text.slice(0,p.start)+p.value+text.slice(p.end);boundary=p.start;}return text;}
export async function applyPlan(ctx,plan){const prepared=preview(ctx,plan),selected=new Map(prepared.plan.edits.map(e=>[e.carrierId,e.toSlideId])),bySlide=new Map(ctx.slides.map(s=>[s.id,s])),changes=[],partPatches=new Map(),relationshipAdds=new Map(),allocated=new Map();
 for(const c of ctx.carriers){const targetId=selected.get(c.id);if(!targetId||targetId===c.currentSlideId)continue;const slide=bySlide.get(c.sourceSlideId),target=bySlide.get(targetId),rels=slide.rels;if(!rels)fail('missing-relationship');let rel=rels.list.find(r=>r.type===RELSLIDE&&r.mode==='Internal'&&r.part===target.part);const key=slide.part+'\0'+target.part;if(!rel&&allocated.has(key))rel=allocated.get(key);if(!rel){let number=1;const additions=relationshipAdds.get(rels.part)??[];while(rels.byId.has('rIdDeckRelay'+number)||additions.some(r=>r.id==='rIdDeckRelay'+number))number++;rel={id:'rIdDeckRelay'+number,type:RELSLIDE,target:'/'+target.part,part:target.part,mode:'Internal'};additions.push(rel);relationshipAdds.set(rels.part,additions);allocated.set(key,rel);}const info=c.node.expandedAttrs[`{${NS.r}}id`];if(!info)fail('patch-attribute');const patches=partPatches.get(c.sourcePart)??[];patches.push({start:info.valueStart,end:info.valueEnd,value:escapeXML(rel.id)});partPatches.set(c.sourcePart,patches);changes.push({sourcePart:c.sourcePart,sourceSlideId:c.sourceSlideId,carrierPath:c.carrierPath,kind:c.kind,oldRid:c.relationshipId,newRid:rel.id,fromSlideId:c.currentSlideId,toSlideId:target.id,fromPart:c.currentPart,toPart:target.part});}
 const bytesByPart=new Map();for(const [part,patches]of partPatches){const slide=ctx.slides.find(s=>s.part===part);bytesByPart.set(part,encode(patchText(slide.doc.text,patches)));}for(const [part,adds]of relationshipAdds){const rels=ctx.slides.find(s=>s.rels?.part===part).rels,prefix=rels.root.name.includes(':')?rels.root.name.split(':')[0]+':':'';const append=adds.map(r=>`<${prefix}Relationship Id="${r.id}" Type="${r.type}" Target="${escapeXML(r.target)}"/>`).join('');bytesByPart.set(part,encode(patchText(rels.text,[{start:rels.root.closeStart,end:rels.root.closeStart,value:append}])));}
 const output=writeZip(ctx.zip,bytesByPart),reopened=await inspectPackage(output,ctx.model.input.name),outById=new Map(reopened.model.carriers.map(c=>[c.id,c]));if(JSON.stringify(ctx.model.slides)!==JSON.stringify(reopened.model.slides))fail('verify-slides');for(const c of ctx.model.carriers){const after=outById.get(c.id);if(!after)fail('verify-carrier');if(selected.has(c.id)){if(after.currentSlideId!==selected.get(c.id))fail('verify-target');}else if(JSON.stringify(c)!==JSON.stringify(after)&&!(c.sharedRelationshipUses!==after.sharedRelationshipUses&&JSON.stringify({...c,sharedRelationshipUses:0})===JSON.stringify({...after,sharedRelationshipUses:0})))fail('verify-unselected');}
 const changedParts=[],media=[];for(const [part,e]of ctx.zip.entries){const after=reopened.zip.entries.get(part);if(!after)fail('verify-parts');const beforeHash=await sha256(e.bytes),afterHash=await sha256(after.bytes);if(bytesByPart.has(part))changedParts.push({part,beforeSha256:beforeHash,afterSha256:afterHash});else if(beforeHash!==afterHash)fail('verify-untouched');if(/(?:^|\/)media\//.test(part)){if(beforeHash!==afterHash)fail('verify-media');media.push({part,sha256:beforeHash,unchanged:true});}}
 const receipt={schema:'deck-relay-receipt-v1',engineVersion:VERSION,inputSha256:ctx.model.input.sha256,outputSha256:reopened.model.input.sha256,planSha256:await sha256(encode(JSON.stringify(prepared.plan))),changes,changedParts,unchangedPartCount:ctx.zip.entries.size-changedParts.length,selectedCount:prepared.rows.length,noOpCount:prepared.rows.filter(r=>r.noOp).length,slideOrder:ctx.model.slides.map(s=>({id:s.id,part:s.part})),media,limits:LIMITS,verification:{reopened:true,unselectedCarriersUnchanged:true,unaffectedEntryBytesIdentical:true,mediaBytesIdentical:true,nativePowerPointTested:false}};return {output,receipt,plan:prepared.plan,model:reopened.model};
}
